"""Utility functions and helpers."""

from .answer_extraction import (
    answers_match,
    calculate_accuracy,
    check_consensus,
    clean_numeric_string,
    consolidate_reasoning_traces,
    detect_sycophancy,
    extract_arc_answer,
    extract_final_answer,
    extract_ground_truth,
)
from .data_utils import (
    deduplicate_data,
    filter_by_length,
    load_jsonl,
    merge_datasets,
    sample_balanced,
    save_jsonl,
    split_dataset,
    validate_data_format,
)
from .helpers import (
    ConfigurationError,
    DataError,
    DebateError,
    DTEError,
    ModelError,
    Timer,
    TrainingError,
    calculate_model_size,
    check_system_requirements,
    clear_gpu_cache,
    create_experiment_directory,
    format_time,
    get_gpu_memory_info,
    get_model_parameter_count,
    robust_retry,
    safe_execute,
    setup_reproducibility,
    validate_device,
    validate_file_path,
    validate_model_name,
)

__all__ = [
    # helpers
    "format_time",
    "calculate_model_size",
    "validate_device",
    "setup_reproducibility",
    "Timer",
    "get_gpu_memory_info",
    "clear_gpu_cache",
    "get_model_parameter_count",
    "DTEError",
    "ConfigurationError",
    "DebateError",
    "TrainingError",
    "DataError",
    "ModelError",
    "safe_execute",
    "robust_retry",
    "validate_file_path",
    "validate_model_name",
    "check_system_requirements",
    "create_experiment_directory",
    # data_utils
    "load_jsonl",
    "save_jsonl",
    "split_dataset",
    "filter_by_length",
    "deduplicate_data",
    "sample_balanced",
    "validate_data_format",
    "merge_datasets",
    # answer_extraction
    "extract_final_answer",
    "extract_ground_truth",
    "clean_numeric_string",
    "answers_match",
    "check_consensus",
    "detect_sycophancy",
    "extract_arc_answer",
    "calculate_accuracy",
    "consolidate_reasoning_traces",
]
